### ISSUE TITLE
Search is broken when the query is < 3 characters

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#107]
**What's the problem you want to solved?** The search page returns all results at once, with a maximum of 64 results, but since they're all returned at once the search is super broken any time that you search for something uncommon. If there are < 64 results, I think the current implementation is just sitting there waiting for more results? I'm not 100% sure.

**Is there a solution you'd like to recommend?** We should probably be streaming results everywhere instead of collecting them in memory and returning them all at once.

**Comment by christianbundy** [comment]
F7U12. The way we're doing templates does *not* seem compatible with streaming HTML interfaces. This is a good thing to learn early in the project, and it's something that we'll likely have to fix. For maximum performance, we want the views to be able to export an HTML stream rather than entire blocks of code. My intuition is that this will make Oasis *very* snappy but might need to be well-documented so it isn't inaccessible for new contributors.

**Comment by christianbundy** [comment]
Nope, SSB-Search is just broken. https://github.com/ssbc/ssb-search/issues/8

**Comment by cinnamon-bun** [comment]
Is this resolved by #141 ?

**Comment by christianbundy** [comment]
Yup, closing now!
