### ISSUE TITLE
The likes page shows stuff that's not liked anymore

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#110]
The page mostly works fine for me but this message that I liked and then unliked (tried to look at who had liked it :P ) still shows up, and twice. I'm guessing it's just displaying every type 'vote' message in my log.

![image](https://user-images.githubusercontent.com/1427063/73308151-efa1d000-421f-11ea-9c32-eaadbffbb9b3.png)

**Comment by christianbundy** [comment]
Nice catch! Really appreciate this bug report. For whoever fixes this, here's the relevant code:

https://github.com/fraction/oasis/blob/82f080f3c6b034ae38eba8a62b04de425b5d088e/src/models/index.js#L536-L590

And here's the correct vote-counting code that's used to display the number of likes on a post:

https://github.com/fraction/oasis/blob/82f080f3c6b034ae38eba8a62b04de425b5d088e/src/models/index.js#L335-L363

Maybe the correct behavior should be abstracted into a function and used in both spots?

**Comment by cbleslie** [comment]
@christianbundy -  Nicety? Shipping with this might cause frustration, but not going to destroy a users experience?
