### ISSUE TITLE
Rename "Meta" to "Preferences"

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#112]
**What's the problem you want to solved?**
Meta is a bit ambiguous. I don't think its immediately obvious to a non-technical user what it refers to.

**Is there a solution you'd like to recommend?**
Rename all references to "Meta" as the boring yet effective "Preferences"

**Comment by christianbundy** [comment]
Hell yeah! I was gonna do "Settings" but felt weird about the indexes and connection info -- those don't feel like preferences to me, hence "Meta", but I think "Meta" is confusing so +1 for improvements.

**Comment by jedahan** [comment]
Extra?
Oasis?
Health?
Health & Looks?
Looks & Behavior?
Health & Behaviour?
Behind the Curtain?

Only some are serious suggestions, and certainly Preferences is better than Meta

**Comment by christianbundy** [comment]
S C U T T L E G U T S

**Comment by christianbundy** [comment]
"DON'T CLICK HERE"

**Comment by jedahan** [comment]
Relatedly, at least one of my mastodon software instances use the word florp for like.

**Comment by jedahan** [comment]
And ideally a lot of the stuff in meta might not need to be there in the far future? Who knows

**Comment by christianbundy** [comment]
Is there specific stuff that you'd like to see moved out? I think eventually we'll need to break that page up into topical pages but I'd love to hear how you think that should be delineated (or where stuff should be moved).

**Comment by jedahan** [comment]
I was more hopeful that in the future having to start and stop the network isn’t as necessary :)

**Comment by christianbundy** [comment]
Resolved by #130 too! So exciting.
