### ISSUE TITLE
Rename "Inbox" to "Messages"

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#116]
**What's the problem you want to solved?**
I think "Inbox" is maybe the wrong term. It reminds people of work and email. Not chatting with other solarpunx. 

Coequally on Scuttleverse the posts are referred to as "Private Messages". Twitter and Facebook both refer to to this feature as Messages and I think we should do the same.

**Is there a solution you'd like to recommend?**
Rename "Inbox" to "Messages" in the main menu.

**Comment by christianbundy** [comment]
Yes! Slightly concerned that 'messages' has a double-meaning since it refers to the payloads we're publishing via SSB in general. Do you think 'private' would be good or nah?

**Comment by jedahan** [comment]
Private feels like a nice mirror of Public, and reinforces the security aspect. Both are improvements

**Comment by cinnamon-bun** [comment]
In #57 we talked about adjusting the views to follow the Gradient of Intimacy, something like

Everyone
People you follow
Mutual friends
Mentions
Private

I think "Private" fits into this sequence a bit more clearly than "Messages".

**Comment by christianbundy** [comment]
Resolved by #130, woo!
