### ISSUE TITLE
Show recipients of private messages

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#126]
**What's the problem you want solved?**
In a private message you can't see who the recipients are, so you can't know the audience you're talking to.

**Is there a solution you'd like to recommend?**
Something like Patchwork, which shows recipient thumbnails in the top right corner of each message?

**Comment by georgeowell** [comment]
I was going to even file an issue suggesting that we redesign the private messages interface entirely. You can probably guess where I'm going with this....

What if it looked really similar to Signal, Facebook messenger, Telegram etc? With that now standard interface of list of threads down the left hand side and thread content on the right.

**Comment by cinnamon-bun** [comment]
Yeah let's try that!

To figure out:
* [ ] Layout on mobile.  Is it possible to make a hamburger-menu drawer using pure CSS?  Maybe using a restyled HTML checkbox as the toggle button
* [ ] If you have multiple threads with the same person would they get combined into a single sidebar item?

I've actually wanted to try kind of layout even for public threads.  Like Thunderbird, a list of threads on the left and the messages in a thread on the right.  I think it might help you keep track of all the threads that are always in play at the same time.

**Comment by georgeowell** [comment]
Manyverse has private messages now and it looks very chat like.

**Comment by cbleslie** [comment]
@christianbundy Show Stopper

**Comment by Powersource** [comment]
uuh how do i assign @lindskog to this issue

**Comment by christianbundy** [comment]
plz don't unassign me

**Comment by christianbundy** [comment]
> uuh how do i assign @lindskog to this issue

GitHub only lets you assign collaborators (trusted folks who have contributed to the repository)

**Comment by Powersource** [comment]
I wanted to assign @lindskog to make it clear to the other new workers that the issue is being worked on.

**Comment by christianbundy** [comment]
Issues can have multiple assignees though.

> make it clear to the other new workers that the issue is being worked on

I'd just comment that. If you *need* this to be searchable with the GitHub UI you can make a custom "powersource knows someone working on this" label or something. Or organize your work with a spreadsheet or something? I'm not sure.

**Comment by christianbundy** [comment]
Just switched my notifications to PRs only, please @mention me if you need my attention in issues. :heart:

**Comment by cbleslie** [comment]
@christianbundy are we there yet? I want a drink of water. @Powersource keeps moving onto my side of the car! /whine

**Comment by lindskog** [comment]
PR for this issue: https://github.com/fraction/oasis/pull/584
