### ISSUE TITLE
Image border boxes visible on transparent images

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#136]
**What's the problem you want solved?**
Images with transparent backgrounds have visible boxes around them:

![Screenshot from 2020-02-01 15-45-51](https://user-images.githubusercontent.com/18296993/73594848-13a82e80-450a-11ea-9ac6-002f5621e308.png)

I tested both png and gif.

**Is there a solution you'd like to recommend?**
Unless this is an accessibility feature, those border boxes shouldn't be visible.

**Comment by christianbundy** [comment]
These were intentional but I'd merge a patch to remove them. I think my concern was that you couldn't see the boundary for transparent images (and images that hadn't loaded) and I wanted to be able to see that, but it's not important or an accessibility feature. Please remove it! :heart:

**Comment by jedahan** [comment]
The only downside I can think of is if people post images that spill over into clickjacking territory - i.e. looking like the app interface. Not sure how this could be abused. I'm all for removing the border boxes and keeping an eye on that.

**Comment by christianbundy** [comment]
@georgeowell Could you be a bit more specific about what the problem you're having is here? Is it that it's confusing, or distracting, or just ugly, or something? Without that it feels like "problem: the wall is green, solution: paint it blue" and I'm not sure what's gained.

**Comment by georgeowell** [comment]
It disrupts the aesthetic you are trying to create with the image. I've just not seen it anywhere else.
