### ISSUE TITLE
Key not found in database

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#144]
**What's the problem you want solved?** If you're missing a message and try to go to the thread then it throws a crappy error message.

```
Error: non-error thrown: {"message":"Key not found in database [%u8t50zvXB/Tj3TTSFxgwKxz6zZS0hyYGpITFSZGL+Q0=.sha256]","name":"NotFoundError","stack":"NotFoundError: Key not found in database [%u8t50zvXB/Tj3TTSFxgwKxz6zZS0hyYGpITFSZGL+Q0=.sha256]\n    at /home/christianbundy/src/fraction/oasis/node_modules/levelup/lib/levelup.js:192:15\n    at /home/christianbundy/src/fraction/oasis/node_modules/encoding-down/index.js:75:21"}
    at Object.onerror (/home/christianbundy/src/fraction/oasis/node_modules/koa/lib/context.js:113:40)
    at onerror (/home/christianbundy/src/fraction/oasis/node_modules/koa/lib/application.js:163:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

I'm seeing this on:

- http://localhost:3000/thread/%25u8t50zvXB%2FTj3TTSFxgwKxz6zZS0hyYGpITFSZGL%2BQ0%3D.sha256
- http://localhost:3000/thread/%25EDeBAjTfkOGGszsSlTLiO7HRCGY1aPTyjKduii2xOMw%3D.sha256

**Is there a solution you'd like to recommend?**

We should be catching this error and providing a more helpful error message.  Even just "This message isn't available, Oasis will look around for it so maybe check back later. You've done nothing wrong" or something would be way better than blowing up..

**Comment by jedahan** [comment]
If this is a normal behavior maybe we can just swallow the message completely? Or if debug is off?

**Comment by christianbundy** [comment]
How do you imagine that looking? Say you post a link to a message to one of your friends, and I click it, and we don't have it in the database. I think without the error we'd just have a completely empty screen -- because how do we find other messages in the thread if we don't know what thread it's in?

**Comment by jedahan** [comment]
Ahh I mistook this error and how it shows up. What you did makes total sense.

I wonder if it would be expensive to validate links and if they are not in the db, unlinkify
