### ISSUE TITLE
Rename Meta to Settings in the code

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#158]
**What's the problem you want solved?**
We renamed Meta to Settings in the UI but not in the URLs or the code.

**Comment by jdjkelly** [comment]
@cinnamon-bun does this include the the the `meta` model? I'm not too familiar with the codebase, so not sure if there's any file IO that's happening with it that could cause issues in a rename.

**Comment by jdjkelly** [comment]
What do you think of a couple of tiny PRs? For example, switching over the URLs is trivial to start with and accomplishes that in one step without risk of breakage.

**Comment by cinnamon-bun** [comment]
@jdjkelly 

It's not anything down at the sbot level, just
* [x] metaView in views/index.js
* [x] URLs

I see you've already done this, thank you!  🌟 

There is a `models.meta` in models/index.js which includes some settings-related things and some other things.  I think we can leave that one alone.
