### ISSUE TITLE
Publish shouldn't be at the top of every page

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#160]
**What's the problem you want solved?** Publish being on the top of all the public pages takes up lots of screen space and 99% of the time I don't want to actually publish anything. I don't really like having to scroll every time I go to a new page.

**Is there a solution you'd like to recommend?** Move publish to its own page, 'Publish'?

**Comment by georgeowell** [comment]
Ah I was going to post an issue about this. 

What if it was a dropdown with the little arrow. It could be just a box saying publish that could be expanding. It would take up like 1/8th of the space.

However there is an issue that arises here that suggests the new Publish page that you have already committed is the way to go.

Currently it may give users the impression that they are only posting to the specific feed they are viewing (i.e. only posting to followers or only posting to the extended network) which isn't true. A general publish page for public messages may be the way to go.

**Comment by jedahan** [comment]
I really like the idea where any place we are about to write something we could share what context it will be seen. Reference to facebooks drop down globe/people icon for public vs friends

**Comment by jedahan** [comment]
I’m also a fan of having the drop down on all pages, encouraging more active contribution vs passive consumption, though that might be reading into it a little too much. See apps that have a floating “+” action
