### ISSUE TITLE
Oasis web demo is out of date

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#166]
**What's the problem you want solved?**
[Web demo](oasis-demo.fraction.io) is out of date.

**Is there a solution you'd like to recommend?**
Update [Web demo](oasis-demo.fraction.io) automatically so potential users/contributors can see more recent improvements. Until we have actual stable packaged releases, it could just update daily via npm.

**Comment by christianbundy** [comment]
So out of date! Unfortunately I was maintaining all of the viewer-specific code in its own branch that respected `publicWebHosting`, but we really just need that merged into `master`. I opened a topic at #48 but it needs some discussion.

**Comment by christianbundy** [comment]
Closing in favor of #48
