### ISSUE TITLE
npm ERR! premature close

### ISSUE THREAD

**Issue by kseistrup** [fraction/oasis#17]
**What version of this package are you using?**

Whichever version is available when saying `npm install -g @fraction/oasis` or doing a `npm install` in git master.

**What operating system, Node.js, and npm version?**

* ArchLinux@5.3.5 (x86_64 GNU/Linux)
* nodejs@12.11.1
* npm@6.11.3

**What happened?**

```
$ npm install
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/$DATETIME-debug.log
```

**What did you expect to happen?**

A successful @fraction/oasis install.

**Are you willing to submit a pull request to fix this bug?**

I don't speak nodejs and I ain't got no clue why this is failing, so: no.

----

:paperclip: [debug.log](https://github.com/fraction/oasis/files/3702319/debug.log)

**Comment by stripedpajamas** [comment]
This is because of the base16 styles dependency that lives in GitHub. If you install dependencies with `yarn` instead of `npm install` it works. `npm` doesn't support installing packages that don't have a package.json (and the base 16 styles one doesn't).

**Comment by stripedpajamas** [comment]
Christian-- if you need that dependency, I think you would have to remove the `npm` option from the readme.

**Comment by kseistrup** [comment]
`yarn` fails on `leveldown` and `sodium-native` (as usual, I might add), but yes: I don't see the “premature close” error when using `yarn`.

**Comment by christianbundy** [comment]
Oh crap, thanks for this bug report! I'll make an npm package with all of the relevant styles rather than using that Git repo. Sorry for the trouble.

**Comment by christianbundy** [comment]
Oops, I sort of meant to close this with my PR but not really?

Anyway, please let me know if you still have this problem and I'll re-open!
