### ISSUE TITLE
Commenting on a private thread only mentions one participant

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#180]
**What's the problem you want solved?**
Commenting on a private thread doesn't select all participants only the person from the post you clicked comment on.

**Is there a solution you'd like to recommend?**
Either automatically select all participants or none and just rely on #167 in the future to know when you get sent a private message. Probably no participants is the best option as #126 suggests a more traditional chat app interface for private messages.

**Comment by christianbundy** [comment]
good point, I think no participants makes the most sense for private threads :+1:

**Comment by christianbundy** [comment]
or maybe all participants would give us an easy way to see everyone else in the thread :thinking: #126

**Comment by cinnamon-bun** [comment]
I feel it's best not to conflate mentions with recipients of private messages, like Patchwork does (inconsistently).

When we have notifications for mentions, we can also have notifications for private messages, so you want me to put a mention inside your private message to get noticed.  Unless you really want to get noticed.
