### ISSUE TITLE
Readme could entice new butts better

### ISSUE THREAD

**Issue by jedahan** [fraction/oasis#192]
**What's the problem you want solved?**
Oasis looks beautiful, and the readme could do a better job at enticing people to try it out.

**Is there a solution you'd like to recommend?**
- [x] Screenshot (of the demo page) in the readme.
- [ ] auto-update screenshot on release?
- [ ] auto-publish release notes on the butts, with newer screenshots?

**Comment by christianbundy** [comment]
See also #59
