### ISSUE TITLE
Don't know what version of oasis I am on

### ISSUE THREAD

**Issue by jedahan** [fraction/oasis#203]
**What's the problem you want solved?**
Sometimes I update oasis, and am not sure if I am on the latest version.

**Is there a solution you'd like to recommend?**
Have a version number in the footer of the settings page
Enhance with a check for the latest semver tag when starting and put the command on how to update next to it if applicable.

**Comment by christianbundy** [comment]
Yup! Yargs has this info, and pulls it with a function called `pkgUp` I think, but I don't think we have a good way of getting the info. And unless you're running with `npm start`, I don't think there are any helpful environment variables or anything either. Hmm.
