### ISSUE TITLE
Editing profile

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#208]
**What's the problem you want solved?** People should be able to set their name, image, and profile description. Right now we can't do this.

- [x] Name
- [x] Description
- [ ] Image

**Is there a solution you'd like to recommend?** Add an 'Edit profile' link to the profile page that gives you a form with three inputs: image, name, and description.

**Comment by cinnamon-bun** [comment]
Also show a privacy warning:

"Note: Old versions of your profile info still exist and are public in the database, though most SSB apps don't show them."

**Comment by georgeowell** [comment]
What are the questions about changing the display picture @christianbundy ? I think you mentioned there was something complex about it.
