### ISSUE TITLE
Can't publish message without content warning

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#211]
**What's the problem you want solved?** Trying to publish a message without a content warning fails the post schema.

**Is there a solution you'd like to recommend?** Only post `contentWarning` if it's a non-zero length string.

**Comment by cinnamon-bun** [comment]
Hooray for schemas!  (Where's the post schema?)

**Comment by christianbundy** [comment]
I think those are in here: https://github.com/ssbc/ssb-schema-definitions
