### ISSUE TITLE
Crash when liking a post if using Patchwork's ssb-server

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#216]
**To reproduce**

1. Start Patchwork first, then Oasis
2. In Oasis, like a post
3. Oasis crashes:
```
/Users/me/projects/ssb/oasis-github/node_modules/ssb-tangle/lib/get-branch.js:27
        cb(null, heads([
        ^

TypeError: cb is not a function
    at /Users/me/projects/ssb/oasis-github/node_modules/ssb-tangle/lib/get-branch.js:27:9
    at /Users/me/projects/ssb/oasis-github/node_modules/pull-stream/sinks/reduce.js:10:5
    at /Users/me/projects/ssb/oasis-github/node_modules/pull-stream/sinks/drain.js:20:24
    at PacketStreamSubstream.weird.read (/Users/me/projects/ssb/oasis-github/node_modules/ssb-client/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/Users/me/projects/ssb/oasis-github/node_modules/packet-stream/index.js:200:12)
    at PacketStream.write (/Users/me/projects/ssb/oasis-github/node_modules/packet-stream/index.js:135:41)
    at /Users/me/projects/ssb/oasis-github/node_modules/ssb-client/node_modules/muxrpc/pull-weird.js:56:15
    at /Users/me/projects/ssb/oasis-github/node_modules/pull-stream/sinks/drain.js:24:37
    at /Users/me/projects/ssb/oasis-github/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/Users/me/projects/ssb/oasis-github/node_modules/packet-stream-codec/index.js:111:11)
```

The like actually goes through and gets saved (it's there when you restart Oasis).

When using Oasis by itself without Patchwork, everything works.

Oasis 2.13.1 from master branch commit e9a7cc5
Node v12.14.1

**Comment by christianbundy** [comment]
Thanks for reporting this! I wonder whether we need to promisify that function :man_facepalming:

**Comment by georgeowell** [comment]
Can recreate.

**Comment by christianbundy** [comment]
Kind of interesting: I tried to recreate this but it looks like I can't even get Patchwork and Oasis running at the same time right now. It says that Oasis is trying to listen on 127.0.0.1:8989, which is the SSB-WS port, but I could've sworn we'd disabled that in `ssb.js`. I looked through the SSB-WS code though and I can't find any reason that our config would disable the server. Weird.

**Comment by christianbundy** [comment]
nvm I had an unrelated error that was being caught by `catch()` and Oasis was starting its own server, which caused the error. Yay, bug hunting!
