### ISSUE TITLE
Hide forks/replies until the user expands them

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#220]
More context in this thread `%YiBecWPnG9iaftO6xRbzsUYxjYOBuZCBI5IEVnH/Uc4=.sha256` , copy pasting some of my thoughts from there to here

**What's the problem you want solved?**

> One issue with [reddit-style thread formatting] that I noticed when trying [oasis] out is that someone made a fork, I assume to not disturb the “main” thread. But since that fork thread was embedded in the main thread it instead took up a lot of space, and if you wanted to read the next message in the main thread you had to scroll all the way past the fork thread.

**Is there a solution you'd like to recommend?**

> One solution could maybe be to by default only show a small preview of the fork, a bit like patchwork, but when you click on it it expands inline and ends up looking sort of like your screenshots above (with maybe a button for un-expanding it again as well). Does that sound like something you’d merge? (not saying I’m gonna implement it :p )

**Comment by christianbundy** [comment]
Thanks for bringing this up! I think this is the right move and I think `<details>` and `<summary>` would be a great way to implement this.

**Comment by Powersource** [comment]
Nice, I was wondering if we could do this without js.

And I just tested, it seems possible to nest `<details>` 🤯

**Comment by Powersource** [comment]
HOLY SHIT I think I made it work?? Pushing in a min

**Comment by Powersource** [comment]
tada https://github.com/fraction/oasis/pull/292
