### ISSUE TITLE
Discussion: Summaries

### ISSUE THREAD

**Issue by ciex** [fraction/oasis#221]
**Preambel**

When I created a [pull request to show previews of a thread next to posts in listings](https://github.com/fraction/oasis/pull/219) @christianbundy noticed that there is a need to discuss summaries in general. I am creating this issue to follow his suggestion and create a place to discuss this issue.

**What's the problem you want solved?**

Discussion in ssb is structured through replies and comments, which create a linked and nested structure of messages. Different clients choose different ways of putting this network of ideas on a screen. Oasis is currently following an approach where listings of posts display individual items without providing information about their context. There is a possibility to enrich this approach by providing a look at the "surroundings" of or reactions to a post in the context of a listing view.

**Is there a solution you'd like to recommend?**

This issue is not aimed at suggesting a specific solution. Please feel free to add your perspective on this situation, link to other project's solutions or make an argument for a direction that should be taken by Oasis.

**Comment by christianbundy** [comment]
Probably repeating myself, but I'd really love to move the summaries into its own page for now and then later add it as an option that can be enabled on any view.

Also, I'm not sure how to best handle this, but the horizontal comments is a bit of an information overload for my brain. My preference would be to keep the design language we've used elsewhere, with comments below the post and indentation to denote sub-conversations, but I also don't want to stomp on anyone's garden.
