### ISSUE TITLE
not sure who has helped out

### ISSUE THREAD

**Issue by jedahan** [fraction/oasis#222]
**What's the problem you want solved?**
the software seems to be created as if by magic, but its actually due to a lot of friendly people

**Is there a solution you'd like to recommend?**
a thank you page somewhere in the software, possibly with links to known ssb ids. would have to be opt-in.

**Comment by christianbundy** [comment]
Maybe we could start with `docs/AUTHORS`? Even just:

```
Jenny Smith <jenny@example.com> 
```

**Comment by christianbundy** [comment]
Might also be worthwhile to codify maintainers in `docs/MAINTAINERS` too, although I don't think we need anything anywhere as complex as [Linux MAINTAINRES](https://github.com/torvalds/linux/blob/master/MAINTAINERS). Just a "these people merge things, hit them up if you need anything". I think I have my email listed in the code of conduct / security policy but it should really be all maintainers.
