### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#238]
**What's the problem you want solved?**
I would like to add french language to oasis

**Is there a solution you'd like to recommend?**
Please tell me where and how to add a translation...

**Comment by cinnamon-bun** [comment]
Thanks @zicmama !

1. Make your own fork of the Oasis repository

2. Add a new language to the list here
https://github.com/fraction/oasis/blob/16f19e85fbff2b656dd0f9f361bb3ae9f9da4e20/src/views/index.js#L794-L797

3. Add translations here, in a new `fr` sub-object.  It uses English as a fallback if a language is not complete yet, so you can work incrementally.
https://github.com/fraction/oasis/blob/16f19e85fbff2b656dd0f9f361bb3ae9f9da4e20/src/views/i18n.js#L4-L12

4. Make a pull request!

**Comment by cinnamon-bun** [comment]
I'm going to close this as an answered question but please keep posting here if you run into any problems!
