### ISSUE TITLE
Not seeing some comments or replies

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#239]
Commit: https://github.com/fraction/oasis/commit/6f5de95d01ebcedeaa2e6002b131ccfe9189f23e

## What's the problem you want solved?
I haven't had much time to troubleshoot but I can see conversations on threads that are missing replies in Oasis that are visible in Patchwork.

For example:
http://localhost:3000/thread/%25lAq%2FMQqiUwpFqUXW3w5Z%2FsM7eOEb7LQymS%2BYXcvwmJ0%3D.sha256#%25lAq%2FMQqiUwpFqUXW3w5Z%2FsM7eOEb7LQymS%2BYXcvwmJ0%3D.sha256

I can only see @christianbundy's responses but not Romulo's. It's like I'm reading only half the conversation.

Is anyone else experiencing this?

## Is there a solution you'd like to recommend?
Investigate whether this can be reproduced and take steps to fix it.

**Comment by georgeowell** [comment]
Ok, this seems to have disappeared after closing and reopening Oasis. I guess we can close this. Perhaps it wasn't fully indexed.

**Comment by christianbundy** [comment]
In the future I'd suggest going to Romulo's profile and seeing if you have their messages yet. My guess is that you just hadn't downloaded them yet, but I'm not sure.
