### ISSUE TITLE
Markdown link not working for %70 message

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#242]
**What's the problem you want solved?** For some reason the Markdown renderer is taking `%70B9TI2hP5QMU59Lx9ozRD5Uh/E7tq4o1Ox8TP07XIg=.sha256` and pointing you to http://localhost:3000/thread/%70B9TI2hP5QMU59Lx9ozRD5Uh/E7tq4o1Ox8TP07XIg=.sha256. That's wrong, and it should be URI encoded as http://localhost:3000/thread/%2570B9TI2hP5QMU59Lx9ozRD5Uh%2FE7tq4o1Ox8TP07XIg%3D.sha256 instead.

**Is there a solution you'd like to recommend?** Nope, not sure why this is broken yet.

**Comment by georgeowell** [comment]
Is this still the case since e7c38e3ec55db1038e70e5432bd2a360db4a32ff

**Comment by christianbundy** [comment]
I believe so, the problem is upstream in SSB-Markdown, reported as https://github.com/ssbc/ssb-markdown/issues/55
