### ISSUE TITLE
what is the use case for --public

### ISSUE THREAD

**Issue by seekr** [fraction/oasis#296]
Other than showcasing Oasis on the web, what is the use case for --public?

Personally, as I experiment with Oasis, I'd love `--public` to let me view my SSB identity from any browser (hosted in a remote server) while protecting it from changes. If I need to post, I'd kill the instances temporarily and run in protected mode just to post. But during that brief time anyone could post for me... So I'd love someway to allow me to "authenticate"

**Comment by christianbundy** [comment]
> Other than showcasing Oasis on the web, what is the use case for --public?

Currently none! The public option is just useful as a public viewer.

> But during that brief time anyone could post for me... So I'd love someway to allow me to "authenticate"

That sounds like a common problem that resonates with me. Would you mind making an issue to describe the problem you have and suggesting a possible solution, if you have ideas? I'm imagining HTTPS + basic HTTP authentication with a password.
