### ISSUE TITLE
Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by mycognosist** [fraction/oasis#30]
**What version of this package are you using?**
2.9.10

**What operating system, Node.js, and npm version?**
Debian: 9.11
Node: 8.9.4
npm: 6.13.4

**What happened?**
After running `oasis`, an error is thrown and the console output stops at `Retrying connection to own server`. The same error is thrown if I try running `oasis` with a Scuttlebutt server already running. The error is: `Cannot read property 'readFile' of undefined`. The full output is as follows:

```
oasis
(node:8086) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'readFile' of undefined
  oasis Initial connection attempt failed +0ms
  oasis Starting Scuttlebutt server +1ms
ssb-friends: stream legacy api used
  oasis Retrying connection to own server +4s
```

**What did you expect to happen?**
Deployment of the oasis web app.

**Are you willing to submit a pull request to fix this bug?**
If I were able to identify and fix the problem, sure. I can see that the `readFile` operation occurs in `index.js` but I'm not sure where `path` is defined.

Thanks for your time and effort, @christianbundy

**Comment by christianbundy** [comment]
Thanks for the awesome bug report.

I think I know what the problem is -- could you upgrade to Node 10? For simplicity I've been targeting the latest active LTS + the latest bleeding-edge Node. I think that's coming from:

```
const { readFile } = require('fs').promises
```

And Node 8 doesn't support promise-based FS.

If there's any reason it's a pain to use Node 10 I'm happy to target Node 8 too -- just let me know.

**Comment by mycognosist** [comment]
Beautiful - it's working!

Ran into some problems trying to upgrade Node and then remembered to use `nvm` instead. Upgraded to Node v12.14.0 and `oasis` came to life. Stoked! Thanks for your terrific support.

**Comment by christianbundy** [comment]
Happy to help! Please let me know if you bump into any other pain points, my brain is warped by familiarity and it makes it hard for me to notice problems. Thanks again!
