### ISSUE TITLE
Version/commit question in issue template

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#320]
## What's the problem you want solved?

Knowing the version/commit is useful for some debugging, but the majority of our issues target master.

## Is there a solution you'd like to recommend?

Remove it or make it optional, maybe? My intuition is that the bigger the template is, the fewer people will follow it, so I'd like to make sure that each question we ask has the same amount of importance.

## What version or commit of Oasis are you using?

latest :grimacing:

**Comment by jedahan** [comment]
I’m down for removing it

**Comment by georgeowell** [comment]
Go ahead.
