### ISSUE TITLE
install docs in the readme aren't up to date with install.md

### ISSUE THREAD

**Issue by justinabrahms** [fraction/oasis#321]
## What's the problem you want solved?
Make the install docs on the readme not use npm as the install.md file says you should install from repo. Also, %bptEc8OnWVXpcQEfG63xEGsz+8xfYmdr140UYSIGq/w=.sha256

**Comment by christianbundy** [comment]
Thanks for reporting this! I'm not sure I understand, could you clarify?

In case it's useful: we're not publishing to the npm registry, but we *do* still have to run commands like `npm install` to pull dependencies.

**Comment by justinabrahms** [comment]
README.md says:

```
First, you'll need Node.js and npm on your computer. Run node --version to see if you have it. If not, or if it's older than the current or active LTS version, you should download Node.js first.

Then you can install the stable version of Oasis:

npm -g install fraction/oasis#semver:

Or, for faster updates and less stability, install Oasis from GitHub and upgrade often.

npm -g install fraction/oasis

Check out install.md for more information.
```

but install.md says:

```
Download Oasis from GitHub over HTTPS.

git clone https://github.com/fraction/oasis.git

Install dependencies

Most people should build and install Oasis with npm.

cd oasis
npm install --only=prod
```

The readme should be updated to not use the npm repository as install.md suggests.

**Comment by christianbundy** [comment]
Oh, I think I understand the problem. The npm CLI lets you install from a GitHub repository with at least three different syntaxes:

- `https://github.com/foo/bar.git`
- `github:foo/bar`
- `foo/bar`

The last one looks *very similar*, but is completely different than `@foo/bar`, which uses the npm registry. Is that helpful, or did I totally miss what you're pointing out?

**Comment by justinabrahms** [comment]
Interesting. So if you do `npm install -g foo/bar` it will actually install from `github.com/foo/bar.git`? That's a surprising feature, but if that's how it works.. so be it.

**Comment by christianbundy** [comment]
Yep, you got it. It's weird and surprising, but I've been hesitant to put the full URL because it's lots more to type (especially when doing weird stuff like Termux installs).
