### ISSUE TITLE
meta refresh on processing errors

### ISSUE THREAD

**Issue by justinabrahms** [fraction/oasis#323]
## What's the problem you want solved?
Right now, I get an error about the system not being done processing. "Sorry, Oasis has only processed xx.x% of the messages and needs to catch up". I'd like to know when it's done.

## Is there a solution you'd like to recommend?
It would be nice if the error page that's rendered in my browser had a [meta refresh tag](https://en.wikipedia.org/wiki/Meta_refresh) which would reload it until it worked.

## What version or commit of Oasis are you using?
2.14.0

**Comment by christianbundy** [comment]
Thanks! This would be really nice. The blocker so far is that I haven't looked into how to render pretty errors with [Koa](https://github.com/koajs/koa), which means that we're dumping all of our errors in plaintext. If we can provide an HTML error page it'd be super simple to add a refresh tag. :+1:

**Comment by christianbundy** [comment]
Also, it may be worthwhile to check the status twice and to give some prediction on when the indexing will be finished.
