### ISSUE TITLE
Connection hops (vs replication)

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#326]
## What's the problem you want solved?

By default, Oasis follows SSB-Config and replicates all feeds within two hops on the social graph. If you follow someone, you'll download their posts *and* the posts of people that they directly follow. SSB-CONN, however, only connects to people that you directly follow (1 hop). This means that if you only follow one person, you'll **only connect with them**. If you're not on the same LAN, you won't connect to anyone. This means that pubs are basically useless, because you'll never connect to them unless you explicitly follow them.

## Is there a solution you'd like to recommend?

I'd like to make our connection hops match our replication hops by default. This means that if you follow someone, you'll connect to them **and the people that they follow**, which you'll also download posts from. This makes pubs become Actually Useful Again.

Alternatively, we could follow Patchwork's current model and only connect to feeds that we follow, and ask the user to explicitly allow connections to anyone past that. This is both inconvenient and, in my opinion, unintuitive, and I'd like to make the number of connection hops be based on the number of replication hops.

## What version or commit of Oasis are you using?

latest

**Comment by georgeowell** [comment]
I think I would be fine with this if for example #328 was implemented. I think it will make it really hard to do the inital onboard when you have to sync for 10 minutes. Related to #274

**Comment by christianbundy** [comment]
Could you add some more info on how this relates to #328? This is only a change to which peers you're allowed to connect to, but shouldn't make a big change the amount of data being exchange.
