### ISSUE TITLE
Improve indentation for threads

### ISSUE THREAD

**Issue by justinabrahms** [fraction/oasis#336]
## What's the problem you want solved?
I find it hard to visually track threads as separate from posts. This is especially true if there's any sort of nesting (which I think I've seen??)

## Is there a solution you'd like to recommend?
Have responses threads be offset a little so the right side is visually distinct from the others.

Example:

![more-offset-oasis-2](https://user-images.githubusercontent.com/3853/77234642-53d07880-6b6d-11ea-959a-cd7cbcb44024.png)

## What version or commit of Oasis are you using?
2.14.0

**Comment by christianbundy** [comment]
Oh, great idea. I think the trade-off is that pages with more indentation end up wider, so they push the left sidebar further to the right, which can feel weird when moving between two pages. Possible solutions:

- Stick the sidebar to the far left side of the page if it fits (i.e. not on small screens). I'm not very excited about this option, but it's basically how operating systems implement their menus. I could imagine a universe where I think a left-justified nav is the most sensible.
- Leave some extra room for indentation. This should be a factor of how many levels of indentation we render by default. Currently this is infinite but "infinity" and user interfaces don't usually get along.
