### ISSUE TITLE
Should we use npm instead of Yarn?

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#34]
**What version of this package are you using?** 2.9.10

**What problem do you want to solve?** I started using Yarn because the lockfile seemed a bit simpler and Yarn seemed to have better support for caching packages for offline reinstalls, but I'm worried that it was the wrong move. While investigating the best systemic solution for #29 I saw some issues (https://github.com/yarnpkg/yarn/issues/2042 and https://github.com/yarnpkg/yarn/issues/3266) that made me skeptical that Yarn is aligned with my values of beginner-friendly behavior.

**What do you think is the correct solution to this problem?** It's super important to me that Oasis is easy and accessible for beginners, and I'd imagine that most beginners are using npm. Should we switch to using `npm` and replace `yarn.lock` with `package-lock.json`?

**Are you willing to submit a pull request to implement this change?** Yes.

cc: @cinnamon-bun @trashhalo  @jjehannet  @mycognosist

**Comment by jedahan** [comment]
Huge fan of npm over yarn, for exactly the same reasons. I used to use yarn a bunch when it was significantly better, but was frustrated making new contributors jump through extra hoops.

**Comment by trashhalo** [comment]
Yarn was key when npm shrink wrap has terribad. These days there is very little light between the two solutions. I see no reason for oasis to stay on yarn.

**Comment by christianbundy** [comment]
Sweet, thanks for all this input. Resolved in f26a148244760bffec19018385e636f8e1f801ff!
