### ISSUE TITLE
Remove pre-commit hook and rely on CI to ensure code quality

### ISSUE THREAD

**Issue by nickwynja** [fraction/oasis#346]
## What's the problem you want solved?

Using pre-commit hooks can be a frustrating developer experience and get in the way of someone's normal development workflow. It can have an unexpected outcome when saving work-in-progress as well as interrupt things like `git rebase` with several unnecessary runs of the linter.

## Is there a solution you'd like to recommend?

Use the existing CI infrastructure to lint on PRs so that code quality is maintained without affecting developer workflow. Alternatively, it could be recommended that developer uses a non-blocking in-editor lint tool.

I'm still reading through [C4](https://hintjens.gitbooks.io/social-architecture/content/chapter4.html) but it looks like it mentions style guides but isn't specific to _how_ they should be implemented or enforced.

## What version or commit of Oasis are you using?

`master`

**Comment by christianbundy** [comment]
Sounds good to me, please feel free to remove them. :+1:
