### ISSUE TITLE
Add command to do complete sync

### ISSUE THREAD

**Issue by nickwynja** [fraction/oasis#354]
## What's the problem you want solved?

As mentioned in `%25b2I4vI7sRFKB5N9iNVv54aNZLWFOI6ioSQ8cKiv0%2B8k%3D.sha256`, I'm looking for a command like `oasis --sync` that can be run to do the following:

1. Start a server or connect to an exist `ssb-server`
1. Start a connection to peers if you aren't already
1. Sync the feed
1. Get `blob.wants`
1. Return the `conn` state to how it was, if previously stopped
1. Kill `ssb-server` if it started one
1. Successfully exit the script with all the things downloaded

I've created [this shell script](https://gist.github.com/nickwynja/721f98b50941fa618c99e9c40548db37) that does much of what I'm looking to do in a pretty messy way. It also repeats much of the core functionality that is done much better in Oasis.

The use case is something like this: someone lives on a boat without any data connection. They come into dock and quickly get a coffee from a cafe before having to leave to do other boat things. They can open their laptop and run `oasis --sync` or have a script that runs `oasis --sync` among several other sync tasks like email before shutting down their machine and getting back to the boat. By having executed the `blob.wants` during the sync script, when this person is back on their boat they are able to have a fully-synced (as of that point in time) offline experience, without missing images or other assets.

## Is there a solution you'd like to recommend?

Something that helps to get a full offline experience.

**Comment by nickwynja** [comment]
Another option could be to have getting `blob.wants` managed as a separate option so, for #328, you could do `oasis --sync --no-blobs`.

**Comment by christianbundy** [comment]
Another way that might be a bit easier to implement: when we're offline, show a "sync" button that:

- Goes online
- Waits for new messages to appear
- Waits for the message count to stop increasing for ~30 seconds
- Goes back offline

**Comment by christianbundy** [comment]
Once we have that, it would be trivial to add a `--sync` command-line option that starts a new server and makes the first action a sync. The only bit that's important to me is that I'd love to avoid needing to turn off the server just to trigger another sync.

**Comment by aadilayub** [comment]
> Another way that might be a bit easier to implement: when we're offline, show a "sync" button that:
> 
> * Goes online
> * Waits for new messages to appear
> * Waits for the message count to stop increasing for ~30 seconds
> * Goes back offline

I'm not sure if this design would be practical in most cases. e.g. someone is traveling and doesn't have access to wifi; if they press the "sync" button in Oasis, it would do nothing, since oasis wouldn't be able to go online and pull data.

Although, I can imagine this design working for people who do have access to the internet but want to minimize their bandwidth usage.

**Comment by nickwynja** [comment]
It would also be nice to have a CLI option for how many hops you want to make so in different bandwidth scenarios, you can choose: `oasis sync --hops 1`.

**Comment by Powersource** [comment]
That PR looks like it solved this issue pretty well for someone using the ui, if I'm understanding it correctly. So what's left in this issue would be to allow it from the CLI? I wonder if we should consider that in scope for this project or if it's maybe better left for another project, such as the shell script linked above?

**Comment by nickwynja** [comment]
I agree that this has been addressed and can be closed. After having spent more time with Oasis and the SSB ecosystem in general I also agree a more command-line-centric approach should be handled by a different tool or project.
