### ISSUE TITLE
Don't show a post's channel twice under the post in the popular view

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#358]
## What's the problem you want solved?

Posts posted *in* a channel (and not just with the channel mentioned) get that channel rendered twice in at least the popular view, like this

![image](https://user-images.githubusercontent.com/1427063/77594825-db184600-6ef7-11ea-935b-10c8c8a9d554.png)

(in some cases people both post in a channel, and tag the channel at the end of the post, but in that case it would look like it's rendered 3 times!)

## Is there a solution you'd like to recommend?

I'm guessing it's a bug, so fix it :P Note, this is unrelated to https://github.com/fraction/oasis/issues/290

**Comment by christianbundy** [comment]
Yep, it looks to me like `transform()` is getting called twice on one message, but an initial skim of the code didn't make it obvious why this is happening.
