### ISSUE TITLE
Lock icon showing up above timestamp

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#361]
## What's the problem you want solved?

![Screenshot_2020-03-26 Oasis](https://user-images.githubusercontent.com/537700/77703911-24f54080-6f79-11ea-959a-c8d063ed1ca5.png)

## Is there a solution you'd like to recommend?

:man_shrugging: Probably some CSS baloney.

**Comment by nickwynja** [comment]
This is probably related to my changes. I don't have any locked (private?) messages so never came across this. I'll take a look.

**Comment by christianbundy** [comment]
Just sent you a private message!

**Comment by christianbundy** [comment]
:muscle:
