### ISSUE TITLE
Make Topics, Summaries and Threads opt in views and move into settings

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#371]
## What's the problem you want solved?
Our menu is just way too crowded and the distinctions between Topics, Summaries and Threads are so small.

## Is there a solution you'd like to recommend?
We have a section in settings where you can toggle each of these views on and off plus the others ones. Then we can add as many new views as we want and users can just choose what they want. We'd start with clear sensible default.s

Somewhere there is a mock up design that @cinnamon-bun made which would be an alternative and perhaps better solution.

**Comment by christianbundy** [comment]
I think this is a dupe of the problem in #170, maybe?

**Comment by georgeowell** [comment]
Yep, just had a bit of a mind fart and couldn't find that issue. Was searching for the wrong words. Closing.
