### ISSUE TITLE
identities, language, etc

### ISSUE THREAD

**Issue by dominictarr** [fraction/oasis#4]
I think it's important that new clients embrace new ssb abilities from the get go. For example, we can now do multiple identities quite easily (using `ssb-identities`) but most clients assume that there is only a single identity.

In yap, I implemented this using cookies - the reason being that it makes the url generic - you could share a link if you wanted to, and it would make sense without knowing the selected user.
(not that you really want to be able to share links, but it seemed like clean design)

I planned the same approach for language. basically, you do a post, which sets the cookie. you just need an ordinary form on the front end.

What do you think? I'm keen to have a back end that can work with oasis and yap.

**Comment by christianbundy** [comment]
I think that's wise, I'm planning to get replies working and then add identity management. It's *probably* the right thing to get identity management working first but I'm in baby-step mode right now.

I think the cookie approach sounds great. Do you have any recommendations for internationalization modules? My only experience has been with Patchwork's system.

**Comment by dominictarr** [comment]
I don't. patchwork has a fairly ad-hoc one, and I wanted to use it. A basic js object seems like it should be enough. I wanted to use the patchwork one, but I found it rather awkward that the key was whole string in english, because if patchwork changes this, all the other objects need to change too. This might work for patchwork, but seems very fragile if you are using it as a dep.

I'd rather have variable names as keys for the messages, so the text descriptions can change easily,
even but the key names stay stable.
```
  "Friends": "Friends",
  "FriendsDescription": "you both follow each other"
```

It just occured to me that if patchwork wanted still use the full string as the key, you could have a thing that just traversed the object to find the english string, grabbed the key, then used that.
