### ISSUE TITLE
How about adding vuejs extra features? 

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#416]
I know that oasis is just HTML and CSS.
No browser JavaScript!

But, I was wondering if you'd like an "option" to activate vuejs or other js modules?
Even is it security reducing, but User eXperience would be greater...

**Comment by christianbundy** [comment]
I think you might have deleted the issue template. Would you mind describing the problem you need to have solved? My understanding is that Vue is an entire UI framework, not a module that we can sprinkle on top of the existing code. Maybe there's another way to resolve the problem you have?

**Comment by Powersource** [comment]
Imma close this since it's not clear what this is fixing (although personally I agree we'll probably need to add clientside js at some point). Reopen if you have more info/input :)
