### ISSUE TITLE
Oasis search not working with ssb-server backend

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#419]
When trying "/search" this is the message received in browser

```
TypeError: Cannot read property 'query' of undefined
    at Object.search (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/models.js:733:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/index.js:315:22
    at async middleware (/home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/index.js:804:7)
    at async /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/index.js:782:5
    at async /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/index.js:777:5
    at async /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/src/http.js:113:5
    at async /home/fred/.nvm/versions/node/v13.8.0/lib/node_modules/@fraction/oasis/node_modules/koa-mount/index.js:52:26
```

**Comment by christianbundy** [comment]
Sorry to hear you're bumping into this.

I don't think this works with SSB-Server, it only works with Patchwork as its back-end. I think it would work with [SSB-Daemon](https://github.com/fraction/ssb-daemon) instead of SSB-Server though.

**Comment by zicmama** [comment]
Thank you.
So your recommandation is Oasis + ssb-daemon + SSB-CLI
I must try...

**Comment by zicmama** [comment]
Following your recommandations %1249ZIXMBdHh2xVE3NuD2cJBgr2utlwg/B6wttfNmb4=.sha256
I have recently installed oasis developement version ```npx global-install fraction/oasis```

It would be preferable I use "stable" 
```
npm -g install fraction/oasis#semver:
```

How can I remove and install oasis?

**Comment by zicmama** [comment]
As I must change my code from sbotc to ssb-client, I wonder if their use is equivalent?
And how difficult switch will be... 

I used to install some ssb-server plugins
https://git.p2p.legal/axiom-team/astroport/src/master/.install/scuttlebutt.sh#L22

Are they included in ssb-daemon?

**Comment by Powersource** [comment]
The original issue here sounds solved? So I'll close this for now
