### ISSUE TITLE
Dependencies documentation

### ISSUE THREAD

**Issue by hamnox** [fraction/oasis#424]
## What's the problem you want solved?
On my new laptop which hadn't had any of the patch* things installed already, I got a stack trace
```
oasis No configuration file found at /home/hamnox/.config/oasis/default.json, using built-in default values. +0ms
error loading sodium bindings: Cannot find module 'sodium-native'
Require stack:
- /home/hamnox/.yarn/lib/node_modules/chloride/bindings.js
- /home/hamnox/.yarn/lib/node_modules/chloride/index.js
- /home/hamnox/.yarn/lib/node_modules/ssb-keys/index.js
- /home/hamnox/.yarn/lib/node_modules/ssb-client/index.js
- /home/hamnox/.yarn/lib/node_modules/@fraction/oasis/src/ssb.js
- /home/hamnox/.yarn/lib/node_modules/@fraction/oasis/src/index.js
falling back to javascript version.
  oasis Listening on http://localhost:3000 +403ms
  oasis Starting Scuttlebutt service +0ms
```
This does not strictly seem like an error, given there *is* a javascript fallback. but it went away when I global-installed sodium-native, so :shrug:

## Is there a solution you'd like to recommend?
add to package.json or have a note in the README

**Comment by christianbundy** [comment]
Could you post the output of `npm ci`? This should've come with Oasis, we don't have any undeclared dependencies that I'm aware of. Sodium-native is an optional dependency we get from chloride ([package.json](https://github.com/dominictarr/chloride/blob/master/package.json)), it looks to me like `npm install` didn't pull it correctly.

**Comment by hamnox** [comment]
Ah, I have the --ignore-optional command set on my global install alias. forgot I'd done that.
