### ISSUE TITLE
How to manage friends connexion ?

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#437]
## What's the problem you want solved?
coming from Patchwork, I have difficulties finding, adding and knowing my friends connexions...

## Is there a solution you'd like to recommend?
Maybe I didn't find the view for it...
I like how https://feedless.social/ is showing it.

**Comment by christianbundy** [comment]
Does #131 describe the problem you're having?

**Comment by zicmama** [comment]
I am not aware of who my actual friends are?
in Patchwork or Feedless I can see them on the side of my Profile view...

**Comment by christianbundy** [comment]
Great, I'm going to close this and continue the discussion in the other thread. Thank you!
