### ISSUE TITLE
No configuration file found ~/.config/oasis/default.json

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#439]
## What's the problem you want solved?
```
oasis No configuration file found at /home/fred/.config/oasis/default.json, using built-in default values. +0ms
  oasis Listening on http://ONELOVE:3000 +2s
  oasis Starting Scuttlebutt service +0ms
ssb-friends: stream legacy api used
```

Is there details on how to make a correct .config/oasis/default.json ?

**Comment by christianbundy** [comment]
Does the documentation need any information added? https://github.com/fraction/oasis/blob/master/docs/configuring.md

**Comment by zicmama** [comment]
Thanks. for documentation link... I miss, what are the parameters I could define?
Other parameters than "port" are existing ?

**Comment by christianbundy** [comment]
Great question. If you run `oasis --help` you'll see all of the parameters, which are also defined in the source code here: https://github.com/fraction/oasis/blob/master/src/cli.js

Right now they're:

- offline
- host
- allow-host
- port
- public
- debug
- theme
