### ISSUE TITLE
Could have more information on Oasis page tittle than just "Oasis"?

### ISSUE THREAD

**Issue by zicmama** [fraction/oasis#441]
## What's the problem you want solved?
I am running multiple oasis sessions, on different "ssb nodes": LOCAL, and remote LAN and WAN (using htpasswd protection for that last case).

When all of them are open in my Firefox browser Tabs, It is difficult to quickly identify them without going to each http://oasis_hostname/profile

## Is there a solution you'd like to recommend?
Display oasis_hostname or title from "about" message on "html page title" would help to make my UX better.

**Comment by Powersource** [comment]
All/most pages should have page-specific titles now. I think that resolves this issue? Comment if it doesn't.
