### ISSUE TITLE
Clicking "Edit profile" link does not load profile-editing form

### ISSUE THREAD

**Issue by SpencerDub** [fraction/oasis#446]
## Bug summary
Clicking the "Edit profile" link in the "😺 Profile" tab loads a blank page with what appears to be the intended content of the profile-editing form inserted into the page's `<title>` tag.

## Steps to reproduce
1. Launch Patchwork (3.17.7.766) on Ubuntu (20.04).
2. Launch Oasis 2.16.0 in Firefox 76.0.1 (64-bit).
3. Click "😺 Profile" in the left-hand navigation bar of Oasis.
4. Scroll to the bottom of the profile and click "Edit profile" to be taken to localhost:3000/profile/edit

## Expected results
A profile-editing page opens.

## Actual results
The left-hand navigation bar remains, but the content of the page disappears. There is no edit form. The `<title>` attribute of the page appears to be replaced with the full content of the `<section>` tags, for instance:

```
<head>
<title>
<section><h1>Edit profile</h1><p>Edit your profile with Markdown. Old versions of your profile information still exist and can't be deleted, but most SSB apps don't show them.</p><form action="/profile/edit" method="POST" enctype="multipart/form-data"><label>Profile image<input type="file" name="image" accept="image/*"></label><label>Profile name (plain text)<input name="name" value="Spencer Dub"></label><label>Profile description (Markdown)<textarea autofocus="true" name="description">[entire content of my profile]</textarea></label><button type="submit">Submit</button></form></section> - Oasis
</title>
```
You can see it in this screenshot:
![Oasis - Profile bug](https://user-images.githubusercontent.com/4674927/82289419-9c33c900-9959-11ea-8988-4f53c7210f60.png)

**Comment by nickwynja** [comment]
@SpencerDub Sorry about this one. Thanks for reporting it! I have a PR open that fixes this.
