### ISSUE TITLE
posting messages

### ISSUE THREAD

**Issue by dominictarr** [fraction/oasis#5]
The approach I used in yap was to have a single POST http api that can create any new message type. I used qs module to parse the query strings so that you can have a nested object, while still using a standard form that works even without javascript enabled.
an app must create a form for the particular messages they create.

This means the application platform is mostly read-only. I hope this will make testing easier.

**Comment by christianbundy** [comment]
I think that's a good call, for `{ type: 'vote' }` messages I gave them their own HTTP endpoint but it might be nicer to just have a single endpoint for all message publishing.

**Comment by christianbundy** [comment]
e.g. the `/like` HTTP endpoint:

https://github.com/fraction/oasis/blob/8713777b6aa42bc974323e30ad3b66ef311734c8/src/pages/like.js#L3-L6

Which uses the *vote* model:

https://github.com/fraction/oasis/blob/8713777b6aa42bc974323e30ad3b66ef311734c8/src/pages/models/vote.js#L4-L13

**Comment by dominictarr** [comment]
this is how I did it in yap,
https://github.com/dominictarr/yap/blob/master/index.js#L86-L102

I havn't done attachments yet... looking at this again I realize I have two separate routes for setting cookies - identitySelect and languageSelect should just be "cookie"

**Comment by christianbundy** [comment]
Should we be mindful of CSRF? I'm thinking about HTML blobs that are going to be running on localhost, which would give an attacker the ability to submit forms to `/apis/publish` and such.

**Comment by dominictarr** [comment]
yes definitely. blobs should be returned with pretty hard CSP settings

**Comment by christianbundy** [comment]
Yeah, all of the relevant code is here: https://github.com/fraction/oasis/blob/b8691d7671afdd62a7f37bf5b94779def30174da/src/app.js#L53-L83

I used `default-src` to disallow everything by default, and manually allowed images, audio/video, and CSS from the same protocol + host + port. The `form-src` tightens down which domains are allowed to send form submissions, and then at the bottom of the code I'm ensuring that the referrer URL exists and doesn't start with `/blob/`.

**Comment by dominictarr** [comment]
that all looks pretty good. did you do any research to come up with this? this is a security thing and you need to get it right the first time. there are probably blog posts about common mistakes...

**Comment by christianbundy** [comment]
Yeah, I've written a bunch of CSPs for proprietary projects (woo) and usually start with the recommendations from [securityheaders.com](https://securityheaders.com/?q=oasis-demo.fraction.io&followRedirects=on), but I've also read through the [OWASP CSRF guide](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) and a handful of the attached pages.

I couldn't find any guides for safely hosting arbitrary HTML on `localhost`, so if you see any I'd be keen to read them. Having a JS-free front-end makes this much simpler than it would be in a conventional application, but I'd still like to make sure all the holes are plugged.

**Comment by dominictarr** [comment]
hmm, I guess the answer is to invoke [cunningham's law](https://meta.wikimedia.org/wiki/Cunningham%27s_Law): write that blog post your self, and let somebody post it on hacker news
