### ISSUE TITLE
Help: Error [OpenError]: IO error: /home/johan/.ssb/flume/time/MANIFEST-000002: No such file or directory

### ISSUE THREAD

**Issue by johanbove** [fraction/oasis#546]
## What's the problem you want solved?

I wanted to send a private post and installed SSB-CLI. I got it finally to run but then ran into trouble trying to post the message. And now that I want to start Oasis again, it fails with the following error output:

```
 $ oasis --allow-host 192.168.0.10
  oasis Configuration read defaults from /home/johan/.config/oasis/default.json +0ms
  oasis Listening on http://localhost:3333 +3s
  oasis Starting Scuttlebutt service +0ms
ssb-friends: stream legacy api used

/home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/src/index.js:108
    throw err;
    ^
Error [OpenError]: IO error: /home/johan/.ssb/flume/time/MANIFEST-000002: No such file or directory
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/levelup/lib/levelup.js:119:23
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
Emitted 'error' event on LevelUP instance at:
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/levelup/lib/levelup.js:60:19
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/levelup/lib/levelup.js:119:14
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    [... lines matching original stack trace ...]
    at /home/johan/.nvm/versions/node/v12.16.3/lib/node_modules/@fraction/oasis/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
```

## Is there a solution you'd like to recommend?
What can I do to get oasis going again?

**Comment by johanbove** [comment]
I will probably need to follow the "refresh" steps described here: https://handbook.scuttlebutt.nz/faq/basics/delete.html

**Comment by black-puppydog** [comment]
Since this is an error in flume, I'd guess that the `log.offset` is fine and you can preserve that instead of re-syncing everything from the network.

**Comment by black-puppydog** [comment]
And wow, I just read that link and this will delete your entire blob storage (which is most of the storage, normally) for no good reason...

If you want to reset flume, you only need to delete everything **except `log.offset`** from `~/.ssb/flume`.
In fact, I've ended up "securing" my `log.offset` by keeping it directly in `~/.ssb/` and only symlinking it into the flume folder:

```
# move the offset log into a safe location
mv ~/.ssb/flume/log.offset ~/.ssb/
# create a symlink to it
ln -s ~/.ssb/log.offset ~/.ssb/flume/log.offset
```

Now, if you absentmindedly `rm -r ~/.ssb/flume` then your offset log will still be there and you just need to symlink it again.

**Comment by christianbundy** [comment]
Personally, I'd just rm -rf ~/.ssb/flume/time` and then try restarting Oasis. That error looks like a corrupt FlumeDB, which will get regenerated.

**Comment by johanbove** [comment]
@black-puppydog Thank you Daan! That seemed to have done the trick. Oasis is now re-indexing. What causes "flume" corruption exactly?

**Comment by johanbove** [comment]
> 
> 
> Personally, I'd just rm -rf ~/.ssb/flume/time` and then try restarting Oasis. That error looks like a corrupt FlumeDB, which will get regenerated.

Thank you Christian as well. Didn't know what to delete there. So many moving parts. Next time I'll remove only the _~/.ssb/flume/time_ folder.

**Comment by christianbundy** [comment]
I don't know why it's corrupt, I've seen it a few times and never seen a cause. :shrug:

**Comment by black-puppydog** [comment]
@christianbundy thanks for chiming in here. I'm never sure what to do with flume except nuke & pave. :laughing: 
Every time I had the itch to get into flume I remembered how many other projects it is being used for and then decided to spend my brain cycles on some other tech. :P
