### ISSUE TITLE
<title> of page is always just "Oasis" -- maybe include thread title

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#55]
**What's the problem you want to solved?**
I like to open lots of Oasis tabs, and also bookmark them for later.  But they all have the same page title, "Oasis".

**Is there a solution you'd like to recommend?**
For message or thread views, put the title of the message/thread in the <title>.

Extracting the message title isn't easy, but maybe:
1. If there's any markdown headlines, use the first one of those
2. Otherwise remove markdown image references in case the message starts with an image, then use the first line of text

**Comment by cinnamon-bun** [comment]
A simpler way to get a message title:

[ssb-markdown](https://github.com/ssbc/ssb-markdown) has a function, `inline`, which renders a message to a single line of text.  Just use the first N characters of that.

**Comment by christianbundy** [comment]
Big +1!

Note to whoever implements this: right now ssb-markdown is doing magic in the 'models' module, which is confusing and backward, but that module is going to be the targt of my next refactor anyway. If you beat me to it, feel free to add ssb-markdown to the 'views' module (assuming that's easier) and I'll deduplicate the code when I refactor.

**Comment by christianbundy** [comment]
Fixed the above, but now the pain is going to be refactoring `template(...elements)` to take `template({ titleSuffix, elements })` or similar. Every time I make a function that doesn't accept named arguments via an object I regret it. :sweat_smile:
