### ISSUE TITLE
Mention Oasis Desktop in the readme

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#575]
## What's the problem you want solved?

Right now a lot of people miss that Oasis Desktop exists and I think that's a shame because that's usually the easiest way to install Oasis.

## Is there a solution you'd like to recommend?

Update the readme in this repo to encourage people to install Oasis using Oasis Desktop.

**Comment by christianbundy** [comment]
Would love to steal the readme section I wrote for Patchwork: https://github.com/ssbc/patchwork#installation
