### ISSUE TITLE
Screenshot in readme

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#59]
**What's the problem you want to solved?** I always really enjoy seeing how software looks before I install it. I was thinking that the web demo would be good enough, but @cblgh asked for a screenshot of Oasis in the readme so that's probably a good idea.

**Is there a solution you'd like to recommend?** Maybe one of us should take a screenshot and put it in the readme? We should probably respect `publicWebHosting` and be sure not to capture any information that the author hasn't said they're okay with sharing. Bonus points for a [slow] animated GIF of some of the themes?

**Comment by jedahan** [comment]
If I could rephrase the problem as “people when discovering oasis may have to invest more effort they are willing to, to try it out” another or an additional solution could be to host as demo or public instance.

**Comment by christianbundy** [comment]
Yep, that sounds reasonable to me. There's a public demo available here, but you can't publish anything: https://oasis-demo.fraction.io/

**Comment by christianbundy** [comment]
Alternatively maybe there's a way to make a link that starts you out on glitch.com? The only pain point is that the Sharp dependency fails and throws a bunch of scary errors on Glitch, and you have to drop into a terminal to `npm install --ignore-optional`. Otherwise, it's way cool that you can get Oasis going on Glitch.

**Comment by jedahan** [comment]
Maybe there’s a way to have that dep be postinstall if PROJECT_DOMAIN is not found

**Comment by christianbundy** [comment]
Hmm, maybe the postinstall isn't the problem? I ran `killall make` repeatedly in another terminal and was able to crash the Sharp build, but npm still exited fine.

```console
$ rm -rf node_modules/sharp
$ npm i                    

> sharp@0.23.4 install /home/christianbundy/src/fraction/oasis/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Detected globally-installed libvips v8.9.0
info sharp Building from source via node-gyp
make: Entering directory '/home/christianbundy/src/fraction/oasis/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
make: *** [sharp.target.mk:151: Release/obj.target/sharp/src/common.o] Terminated
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: null
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.14-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/christianbundy/src/fraction/oasis/node_modules/sharp
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
../src/common.cc:27:10: fatal error: common.h: No such file or directory
compilation terminated.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.23.4 (node_modules/sharp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 8267 packages in 7.589s

54 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```
