### ISSUE TITLE
Unable to change theme

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#60]
## Browser: 
Firefox Browser 72.0.1
Chromium Version 79.0.3945.79

## What's the problem you want to solved?
I wanted to change the theme. I go to "meta" and change to any of the other themes.

## What happens?
I am redirected to an error:

```
ReferenceError: URL is not defined
    at router.param.param.param.param.get.get.get.get.get.get.get.get.get.get.get.get.get.get.get.get.get.get.get.post.post.post.post.post.post.post (/usr/local/lib/node_modules/@fraction/oasis/src/index.js:512:21)
    at dispatch (/usr/local/lib/node_modules/@fraction/oasis/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/usr/local/lib/node_modules/@fraction/oasis/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /usr/local/lib/node_modules/@fraction/oasis/node_modules/koa-body/index.js:148:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The theme is not changed.

**Comment by christianbundy** [comment]
Dang, that doesn't look fun at all. Thanks for posting this bug report so that other people don't bump into the issue. Could you post the Node.js version you're using? That error suggests to me that you're on Node.js 7 or earlier -- if that's true, could you upgrade to at least Node 10 and see if that resolves the problem?

**Comment by georgeowell** [comment]
I was using the version in the Ubuntu repos for 18.04 which is `nodejs/bionic-updates,now 8.10.0~dfsg-2ubuntu0.4 amd64` and horrendously old.

So I just tried with Node `10.16.1` and now I can't get Oasis running. I also get the same error with node version 

`oasis --open` was failing with
```
Something went wrong installing the "sharp" module

The module '/home/leo/git/oasis/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

- Ensure the version of Node.js used at install time matches that used at runtime
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```
I'm not very knowledgeable in this area so I didn't know I had to run `node rebuild`. After doing that I can change the theme!

**Comment by christianbundy** [comment]
Happy to hear that you have it working now, thanks for this update!
