### ISSUE TITLE
Sometimes connects to peers but doesn't get new messages

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#63]
**What's the problem you want to solved?** https://github.com/staltz/ssb-conn/issues/11

**Is there a solution you'd like to recommend?** Maybe as a stopgap it would be wise to just add a "reset networking" button to the 'meta' page? I've been running `ssb gossip reconnect` in my terminal but I don't want people to have to use a terminal to workaround Oasis problems.

**Comment by jedahan** [comment]
Reset networking is nice, maybe call it 'force refresh' or 'scan for new connections'. One question is how we illuminate when to press the button. Perhaps if, 5 minutes after starting, if the latest message is over 3 days old, and no new messages are found, point out the refresh button?

**Comment by cinnamon-bun** [comment]
I've seen this happen in Patchwork also.

A button on the Meta page sounds good.

**Comment by christianbundy** [comment]
Closing after workaround from #92
