### ISSUE TITLE
Show peer names in Meta & explain what's happening there

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#68]
**What's the problem you want to solved?**
The Meta page shows peers I'm connected to, but only by their pubkey.

**Is there a solution you'd like to recommend?**
Instead of pubkey, show their names.

While we're revamping this, it's also a good time to add a bit of help text.  People tend to be confused about peer network connections vs. social following connections.  I've seen them get scared, saying "who's this person looking at me??  How did they find me?"

Maybe something like...

**Peer connections 💻⚡️💻**
*Your computer is syncing data with these other computers.  It will connect to any scuttlebutt pub and peer it can find, even if you have no relationship with them, as it looks for data from your friends.*
* `@foo`
* `@bar` 

(That's adapted from part of the [scuttlebutt.nz help text](https://scuttlebutt.nz/docs/introduction/detailed-start/#what-are-all-these-pubs-listed-in-the-patchwork-sidebar-i-didn-t-join-those) which I wrote)

**Comment by cinnamon-bun** [comment]
That PR adds help text but not peer names.  I'm not sure how to look up the names.

**Comment by christianbundy** [comment]
> I'm not sure how to look up the names.

Happy to support you working on this. You'll probably want to edit `src/index.js` to use [this code](https://github.com/fraction/oasis/blob/2adcede85f9a1155c9b3bdf0e13007f13846cc5d/src/models/index.js#L31-L39):

```js
const feedName = await about.name(feedId)
```
