### ISSUE TITLE
Conversation: Typescript

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#78]
I'm interested in converting some code to Typescript.  Thoughts?

![pipe-labels](https://user-images.githubusercontent.com/32660718/73108438-39538900-3eb5-11ea-8d68-d41bfa72733c.jpg)

Labeling your types makes it possible to understand code by looking locally, in one file, instead of having to read the whole project and keep it all in your head at once.  

For example when I wanted to add names to the peer list, I looked at code like this:
https://github.com/fraction/oasis/blob/master/src/views/index.js#L177

and had no idea what kind of thing a `peer` was or what properties it had.  I ran it with a `console.log` to find out, but that only showed me some of the possible variations of peer objects according to who was online at that moment.

Personally I find lack of types to be the biggest challenge in understanding SSB code.  It's a challenge to figure out which of the many modules are generating objects in the first place.

**Upsides**
* Easier to understand code, for people who can read Typescript
* Fewer bugs at runtime

**Drawbacks**
* Contributors have to be able to read Typescript
* Another dependency, another config file
* Adds a build step (or use [ts-node](https://github.com/TypeStrong/ts-node) as a drop-in replacement for `node` which compiles for you)

There's also a middle path, [adding types in comments](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) within plain Javascript files.  This has its own different syntax that fewer people know, I think, but lets you run the code with no build step.
```
/** @type {string[]} */
const x = [];
```

I use TS in all my own projects and feel it helps a lot, but here the choice doesn't seem obvious.  I'm not pushing for it, but if others are excited I can help.

**Comment by christianbundy** [comment]
Thanks for opening this discussion. I like TypeScript, and I've used it professionaly, but I've been on the fence regarding whether I'd like to make "learn TypeScript" a mandatory part of working on Oasis.

I'd be super supportive of adding TypeScript comments to the plain JS, and I think that would be an unambiguous win. JSDoc-style comments are well-known and supported by lots of tooling, and I think it'd be great to start adding types that way.

**Comment by christianbundy** [comment]
Is this still a problem you'd like to keep open?

**Comment by cinnamon-bun** [comment]
We can close this issue now.  I'd like to experiment more with typing via JSDoc comments but haven't had the energy yet.
