### ISSUE TITLE
Standardise/appropriate menu layout

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#91]
Hate to be that person but we should more closely match the layout of existing social network clients to meet user's expectations. For clarification, I am referring to where we display menu options "popular latest inbox... etc".

I personally think we should be really boring here and either have a Facebook style "bar" across the top or some sort of Mastodon style split thing either on both sides of the feed or to a specific side.

## Mastodon v3.0.1
![masto_v3](https://user-images.githubusercontent.com/18296993/73143292-5a240600-4090-11ea-8300-12cf1ed0b175.jpg)

## Oasis mock-up (nord theme)
![oasis_menu_mockup](https://user-images.githubusercontent.com/18296993/73143374-285f6f00-4091-11ea-9b8a-9c1334d9a628.jpg)
This is my very ropey mock-up :smile: I think this looks really clean though.

**Comment by christianbundy** [comment]
I agree! Did you see the discussion in #28 alreadt?

**Comment by georgeowell** [comment]
Ooo I'm sorry I missed that. Could we merge or shall I just cross post and then close this issue?

**Comment by christianbundy** [comment]
No problem, I'll close this and we can discuss over there. FWIW, I really dig your sidebar mockup.
