### ISSUE TITLE
Sidebar nav should have relatively fixed x coordinates

### ISSUE THREAD

**Issue by jedahan** [fraction/oasis#96]
**What's the problem you want to solved?**
Its mildly frustrating when navigating with the sidebar, having clickable elements move horizontally. Makes navigation require movement in two directions instead of one.

**Is there a solution you'd like to recommend?**

I can only think of two solutions right now

* have fixed width breakpoints where all the columnar main content is the same width
* have the main content left align, but allow for variable width

**Comment by christianbundy** [comment]
Thanks for reporting this, but I'm not sure I understand 100%. Is this happening on the search page? If so, I just pushed a commit that might resolve that.

**Comment by jedahan** [comment]
I think I was getting a little ahead of merging the other PR #95  instead of mentioning a possible improvement my plan was to merge that then solve this as an improvement

**Comment by christianbundy** [comment]
Oh, sounds like we noticed the bug around the same time! FWIW that branch still has this bug, it's just very minor and only seems to happen on the search page.

**Comment by jedahan** [comment]
fixed in #95
