### ISSUE TITLE
Oasis user onboarding stratergy

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#97]
Me again :smile: 

Scuttlebutt clients in general don't make it easy to onboard people. I think this should be one of the main focuses of Oasis (along with awesome user safety features #93). 

Support for ssb-rooms would be handy. @arj03 has also been working on some really cool stuff with ssb-browser. I wonder if we can leverage some of these technologies. Here is [a demo](https://between-two-worlds.dk) of ssb-browser.

Here are some rough ideas of how to improve the experiance over previous clients:

## SSB Rooms 
Support for SSB room would help new users connect remotely or in different network conditions.

https://github.com/staltz/ssb-room/
https://www.manyver.se/blog/announcing-ssb-rooms

## Partial replication
It's a real pain for new users to have to wait 15 minutes to do the initial sync after making their first connections on the Scuttleverse. 

> Partial replication is done by only getting the last few post messages for users as a way of onboarding users quickly. The client can download and index around 5.000 messages in 30 seconds on my really slow laptop (roughly same speed on a phone). For this, a blob (generate-onboarding-json.js) must be provided that serves as a trusted onboard mechanism.

> This will provide an initial load of data and people. You then sync the feeds of these people, but selective sync can be done by following people directly.

> The ssb-partial-replication plugin is needed for faster sync. Also the ssb-get-thread plugin is used for browsing threads you don't currently have, such as from people outside the people you have synced or older messages because of the partial replication nature.

https://github.com/arj03/ssb-browser-demo
https://github.com/arj03/ssb-partial-replication
https://github.com/arj03/ssb-get-thread
https://github.com/ssbc/ssb-contact-msg

## Peer invites
A way to help bring people onto the Scuttleverse with a personalised invite.

> Peer invites is another way to onboard people. The client allows one to generate and use peer invites. The invites can include an list of people to follow beside the user that created the invite. In doing so, these invites serves the same function as the onboarding blob.

https://github.com/arj03/ssb-browser-demo#peer-invites

<strike> ## Onboarding blob
A way to help people follow all the people you are following or some combination of such.

https://github.com/arj03/ssb-browser-demo#onboarding-file</strike>

**Comment by arj03** [comment]
Hi

Rooms are interesting, I might add that to ssb-browser demo as well. The offchain chat feature in ssb browser uses tunnels, the same as rooms, so it shouldn't be that hard.

Partial replication is probably not something we are going to have in "normal" ssb applications. The partial replication features are highly experimental and really makes the most sense when we have something like bamboo because then we can be sure that we don't have forked feeds. That being said I think [ssb-contact-msg](https://github.com/ssbc/ssb-contact-msg) would be nice to adopt. Again this was mostly to put something in place that we SHOULD have when introducing a new feed format :)

Peer invites: yes please, we need more clients with support for this. Honestly I sometimes wonder how somehow would stay on SSB after connecting to a random pub and downloading thousands of random profiles data before being able to really do anything.

Onboarding file: I think peer invites mostly solves this now if it is implemented the way I did in in ssb browser where one can add profiles to the invite. There is a thread with some nice screenshots about how this works on SSB under the #ssb-browser hash tag.

**Comment by christianbundy** [comment]
Yup, big +1 on peer invites.

**Comment by georgeowell** [comment]
@arj03 I almost made a separate issue for off-chain chats! It's such a cool concept.

I do think it would be awesome for Oasis in the long term. Literally just some super cool P2P Facebook messenger private mode. Even less meta-data that private messages and totally disappears after the chat is done.

**Comment by christianbundy** [comment]
> I think perhaps I should close this issue and make separate issues for the specific features.

Just a note: I'm working on Oasis on nights and weekends and lunch breaks so my energy is pretty limited. Feature requests that are big and long-term are probably not something that *I* will be able to take care of, although others might be able to help. The things that are on my mind are critical bits like:

- hide blocked users from feeds
- refactor weird code to make Oasis easy for beginner devs to pick up
- give people *any* way to onboard
- add a way to upload blobs
- add a way for people to change their name/description
- etc

There's lots of utility in maintaining a long-term vision for the project, but right now I'm really trying to make sure that we have all of the basics. Would you be interested in helping find / solve some of the problems that would help get us to feature / usability parity with Patchwork? Or maybe we could have some documentation on the vision / philosophy of the project and where we want to go? My fear is that we keep accumulating feature requests that are always out-of-reach, which feels bad.

Hope this comes off the right way, I'm really excited to see all of these contributions to the project and I want to make sure that issues aren't being ignored. :heart: :heart: :heart:

**Comment by jedahan** [comment]
> Or maybe we could have some documentation on the vision / philosophy of the project and where we want to go?

Yesterday I wrote a long issue and didn't post it, regarding trying to understand the goals of the project. With diverse contributors we get diverse wants and contexts, and having at least a vision is a great idea. What I found is that the first sentence of the readme felt like the light-weight vision statement, so I deleted that post.

The gist boiled down to: "Can we succinctly describe what we currently want oasis the software to look like?" and "Can we succinctly describe what we wish oasis the community to feel like?".

> My fear is that we keep accumulating feature requests that are always out-of-reach, which feels bad.

First of all, thank you for stating upfront this is a nights-and-weekends passion project. First step to avoid burnout is to recognize ones own limitations (first of all time). I was actually under the impression you spent the majority of you time on this and was surprised to hear this was not the case. <3
---
regarding vision:

I really am attracted to the current description, of course calcifying any one-sentence vision is not the best thing.

> Friendly Scuttlebutt interface designed for simplicity and accessibility

This doesn't capture all the nuance (what is simplicity?), but I would love to see just how far we can take it.

**Comment by jedahan** [comment]
It’s a really positive sign that so much energy is summoned so quickly for this project - and even better that we have a high amount of communication documenting that energy which makes me believe this is the start of a lasting, sustainable project.

I am not sure posting on ssb is better, there’s pros and cons to that. For one I think I would not be nearly as responsive on ssb (though with ssb running as a daemon I am more up to date than usual)

**Comment by christianbundy** [comment]
> I hope it doesn't seem like I am demanding features.

Not at all, sorry for the misunderstanding there. I've written this message like six times and can't get the wording right, but basically: I'm very happy about the thoughtful work you've been pouring into this project, I think I'm just feeling some stress when I see big pieces of work that I can't immediately break down into bite-size chunks. It's just a me thing, you're great.

If my brain comes up with better words later I'll add them, but for now:

:heart: :sparkles: :heart: :sparkles: :heart: :sparkles:

**Comment by christianbundy** [comment]
Also +1 for not trying to plan/develop/etc Oasis on SSB -- I'm hoping that #49 helps, but currently I'm feeling like I can't keep my notifications straight and it's impossible to remember who I've replied to and who I've been ignoring.

**Comment by georgeowell** [comment]
Yeh don't feel pressure to reply to anything. 

I concur, Github notifications are terrible! I almost feel like interacting with issues via email is actually almost better.

Perhaps there could be another tag which is something like "fluffy" or "speculative" or what not which is for issues about "enhancements" that aren't very focussed. IDK how this works :smile:

**Comment by jedahan** [comment]
stream-of-consciousness GitHub label
or “random thought” or “unconsidered”
