### ISSUE TITLE
Switch to capitalised first letters in menu

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#98]
**What's the problem you want to solved?**
Items in the menu and the submit button don't have the first letter capitalised. This kinda stands out seems unusual to me. 

**Is there a solution you'd like to recommend?**
Switching as general rule to capitalising the first letter unless there is a specific reason to have it that way.

**Comment by christianbundy** [comment]
Thanks for bringing this up! Could you help pinpoint which menu you mean? There's both the navigation menu and the actions that you can do on each individual message. Or both?

Background: I used to have the message menu capitalized but I thought it looked weird and unbalanced. Lately I've been leaning toward all-caps actions, like how material design does it, but I haven't had time to experiment with it. It may be useful to know that lots of design cues have been influenced by news.ycombinator.com, for better or worse. :grimace

**Comment by christianbundy** [comment]
Btw, I really appreciate the way that you identified a problem that you're having and suggested a small baby step in the right direction. There's tons of power in small iterative changes and it makes for a nice environment for writing and reviewing code.

**Comment by georgeowell** [comment]
I think just sticking to a consistent pattern for this throughout. It would be great to get some icons up in there also. 

news.ycombinator.com is probably not the best thing to base our design from my perspective :sweat_smile:

**Comment by christianbundy** [comment]
> I think just sticking to a consistent pattern for this throughout.

Yup! If you haven't already seen it, I'd love your feedback on #99.

> It would be great to get some icons up in there also.

Yep, at least some emoji would be great IMO.

**Comment by georgeowell** [comment]
Closing due to https://github.com/fraction/oasis/pull/99
